import QSB.ByteLatePuzzle

/-!
A necessary NULLDUMMY condition for the last final-round bonus roll. This is
local to an arbitrary byte stack at that roll. If the cell at source depth 10
is nonempty, selecting any depth below 10 moves it into the eventual dummy
slot, so the remainder of the generated byte program cannot succeed.

The earlier selection loop must still establish the required nonempty cell
and the source of the chosen signature for arbitrary accepted witnesses.
-/
namespace QSB.FinalBonusBoundary
open ByteMachine
open ByteLatePuzzle
set_option maxRecDepth 20000
set_option maxHeartbeats 10000000

/-- For a roll selecting one of the first ten cells, the old cell at depth
ten becomes the post-roll cell at depth ten. No assumption about the rest of
the stack or the values of the selected cells is needed. -/
theorem shallow_roll_tenth_source {α : Type*}
    (region rolled : List α) (n : Nat) (hn : n < 10)
    (run : KeyRolls.rollAt n region = some rolled) :
    rolled[10]? = region[10]? := by
  unfold KeyRolls.rollAt at run
  cases hget : region[n]? with
  | none => simp [hget] at run
  | some chosen =>
      simp [hget] at run
      cases run
      simpa using
        (List.getElem?_eraseIdx_of_ge (l := region) (i := n) (j := 9)
          (by omega))

/-- A roll at depth ten or deeper leaves the old cell at depth nine as the
post-roll cell at depth ten. -/
theorem deep_roll_ninth_source {α : Type*}
    (region rolled : List α) (n : Nat) (hn : 10 ≤ n)
    (run : KeyRolls.rollAt n region = some rolled) :
    rolled[10]? = region[9]? := by
  unfold KeyRolls.rollAt at run
  cases hget : region[n]? with
  | none => simp [hget] at run
  | some chosen =>
      simp [hget] at run
      cases run
      simpa using
        (List.getElem?_eraseIdx_of_lt (l := region) (i := n) (j := 9)
          (by omega))

theorem modeled_shallow_bonus_tenth_source (hashes : Hashes)
    (raw : Bytes) (region : List Bytes) (n : Nat)
    (outcomes : List Bool) (cost : Nat) (postBonus : State)
    (hn : n < 10)
    (decoded : ByteIndex.parseScriptNum raw = some (Int.ofNat n))
    (roll : run hashes [.roll]
      (State.mk (raw :: region) outcomes cost) = some postBonus) :
    postBonus.stack[10]? = region[10]? := by
  obtain ⟨afterRoll, rolled, _, finished⟩ :=
    FirstAcceptedOrigin.run_cons_success hashes .roll []
      (State.mk (raw :: region) outcomes cost) postBonus roll
  have budget := ByteFinalCounts.roll_success_budget hashes raw region
    outcomes cost afterRoll rolled
  rw [FirstOvershoot.byte_roll_matches_list_roll hashes raw n region
    outcomes cost decoded budget] at rolled
  cases hroll : KeyRolls.rollAt n region with
  | none => simp [hroll] at rolled
  | some rolledStack =>
      have source := shallow_roll_tenth_source region rolledStack n hn hroll
      simp [hroll] at rolled
      cases rolled
      simp [run] at finished
      cases finished
      exact source

theorem modeled_deep_bonus_tenth_source (hashes : Hashes)
    (raw : Bytes) (region : List Bytes) (n : Nat)
    (outcomes : List Bool) (cost : Nat) (postBonus : State)
    (hn : 10 ≤ n)
    (decoded : ByteIndex.parseScriptNum raw = some (Int.ofNat n))
    (roll : run hashes [.roll]
      (State.mk (raw :: region) outcomes cost) = some postBonus) :
    postBonus.stack[10]? = region[9]? := by
  obtain ⟨afterRoll, rolled, _, finished⟩ :=
    FirstAcceptedOrigin.run_cons_success hashes .roll []
      (State.mk (raw :: region) outcomes cost) postBonus roll
  have budget := ByteFinalCounts.roll_success_budget hashes raw region
    outcomes cost afterRoll rolled
  rw [FirstOvershoot.byte_roll_matches_list_roll hashes raw n region
    outcomes cost decoded budget] at rolled
  cases hroll : KeyRolls.rollAt n region with
  | none => simp [hroll] at rolled
  | some rolledStack =>
      have source := deep_roll_ninth_source region rolledStack n hn hroll
      simp [hroll] at rolled
      cases rolled
      simp [run] at finished
      cases finished
      exact source

/-- Exact local NULLDUMMY source dichotomy. The last bonus index must use an
empty cell at source depth 10 if it selects a shallow cell, or at source depth
9 if it selects a deep cell. No distinctness, canonical-witness, or hash
assumption is used. -/
theorem successful_bonus_empty_source_dichotomy (hashes : Hashes)
    (raw : Bytes) (region : List Bytes) (n : Nat)
    (outcomes : List Bool) (cost : Nat) (postBonus final : State)
    (decoded : ByteIndex.parseScriptNum raw = some (Int.ofNat n))
    (roll : run hashes [.roll]
      (State.mk (raw :: region) outcomes cost) = some postBonus)
    (suffix : run hashes (ByteLayout.program.drop 850)
      postBonus = some final) :
    (n < 10 ∧ region[10]? = some []) ∨
      (10 ≤ n ∧ region[9]? = some []) := by
  cases postBonus with
  | mk postStack laterOutcomes laterCost =>
      have empty := accepted_generated_postbonus_dummy_empty hashes
        postStack laterOutcomes laterCost final suffix
      by_cases shallow : n < 10
      · have source := modeled_shallow_bonus_tenth_source hashes raw
          region n outcomes cost (State.mk postStack laterOutcomes laterCost)
          shallow decoded roll
        exact Or.inl ⟨shallow, source.symm.trans empty⟩
      · have deep : 10 ≤ n := by omega
        have source := modeled_deep_bonus_tenth_source hashes raw
          region n outcomes cost (State.mk postStack laterOutcomes laterCost)
          deep decoded roll
        exact Or.inr ⟨deep, source.symm.trans empty⟩

/-- If both neighboring candidate dummy sources are nonempty, no choice of
last bonus index can complete the modeled generated suffix. -/
theorem two_nonempty_dummy_sources_reject (hashes : Hashes)
    (raw : Bytes) (region : List Bytes) (n : Nat)
    (outcomes : List Bool) (cost : Nat) (postBonus final : State)
    (nine ten : Bytes) (nineNonempty : nine ≠ []) (tenNonempty : ten ≠ [])
    (atNine : region[9]? = some nine) (atTen : region[10]? = some ten)
    (decoded : ByteIndex.parseScriptNum raw = some (Int.ofNat n))
    (roll : run hashes [.roll]
      (State.mk (raw :: region) outcomes cost) = some postBonus)
    (suffix : run hashes (ByteLayout.program.drop 850)
      postBonus = some final) : False := by
  rcases successful_bonus_empty_source_dichotomy hashes raw region n
    outcomes cost postBonus final decoded roll suffix with
    ⟨_, emptyTen⟩ | ⟨_, emptyNine⟩
  · rw [atTen] at emptyTen
    exact tenNonempty (Option.some.inj emptyTen)
  · rw [atNine] at emptyNine
    exact nineNonempty (Option.some.inj emptyNine)

/-- A necessary index bound with arbitrary earlier stack contents. It needs
only one local premise: the cell at source depth ten is nonempty. The entire
generated program after the last bonus roll enforces NULLDUMMY, so selecting
any of source depths zero through nine cannot complete. -/
theorem successful_bonus_requires_depth_at_least_ten (hashes : Hashes)
    (raw : Bytes) (region : List Bytes) (n : Nat)
    (outcomes : List Bool) (cost : Nat) (postBonus final : State)
    (marker : Bytes) (nonempty : marker ≠ [])
    (atTen : region[10]? = some marker)
    (decoded : ByteIndex.parseScriptNum raw = some (Int.ofNat n))
    (roll : run hashes [.roll]
      (State.mk (raw :: region) outcomes cost) = some postBonus)
    (suffix : run hashes (ByteLayout.program.drop 850)
      postBonus = some final) :
    10 ≤ n := by
  by_contra tooSmall
  have shallow : n < 10 := by omega
  have displaced := modeled_shallow_bonus_tenth_source hashes raw region
    n outcomes cost postBonus shallow decoded roll
  cases postBonus with
  | mk postStack laterOutcomes laterCost =>
      have empty := accepted_generated_postbonus_dummy_empty hashes
        postStack laterOutcomes laterCost final suffix
      rw [displaced, atTen] at empty
      have equal := Option.some.inj empty
      exact nonempty equal

end QSB.FinalBonusBoundary
