import QSB.FirstNegativeAll

/-!
The bridge from a successful generated byte-machine run to first-selection
commitment provenance. This remains a byte-model theorem for the specified
initial top-stack layout and granted pinning outcomes, not a Core theorem.
-/
namespace QSB.FirstAcceptedOrigin
open ByteMachine
open FirstOvershoot
set_option maxRecDepth 20000
set_option maxHeartbeats 10000000

theorem run_cons_success (hashes : Hashes)
    (op : Op) (ops : List Op) (initial final : State)
    (accepted : run hashes (op :: ops) initial = some final) :
    ∃ next,
      step hashes op initial = some next ∧
      next.stack.length ≤ 1000 ∧
      run hashes ops next = some final := by
  unfold run at accepted
  cases stepped : step hashes op initial with
  | none => simp [stepped] at accepted
  | some next =>
      by_cases large : next.stack.length > 1000
      · simp [stepped, large] at accepted
      · refine ⟨next, rfl, by omega, ?_⟩
        simpa [stepped, large] using accepted

theorem successful_prefix (hashes : Hashes)
    (before after : List Op) (initial final : State)
    (accepted : run hashes (before ++ after) initial = some final) :
    ∃ middle, run hashes before initial = some middle := by
  rw [run_append] at accepted
  cases middle : run hashes before initial with
  | none => simp [middle] at accepted
  | some state => exact ⟨state, rfl⟩

def firstThree : List Op :=
  [.push [0x2e, 0x01], .roll, .push [0x98, 0x00]]

theorem first_selection_split_three : firstSelectionPrefix =
    firstThree ++ [.min, .dup, .push [0x97, 0x00], .add, .roll,
      .push [0x37, 0x01], .roll, .hash160, .equalverify] := by decide

theorem first_three_run (hashes : Hashes)
    (raw : Bytes) (tail : List Bytes) (outcomes : List Bool)
    (small : tail.length ≤ 696) :
    run hashes firstThree
      (State.mk (fixedRegion ++ raw :: tail) outcomes 5) =
      some (State.mk ([0x98, 0x00] :: raw :: (fixedRegion ++ tail))
        outcomes 6) := by
  unfold firstThree run step
  simp
  constructor
  · rw [fixed_region_length]
    omega
  · unfold run
    rw [byte_roll_matches_list_roll hashes [0x2e, 0x01] 302
      (fixedRegion ++ raw :: tail) outcomes 5 (by decide) (by omega)]
    rw [first_index_roll_any_tail]
    simp
    constructor
    · rw [fixed_region_length]
      omega
    · unfold run
      unfold step
      simp
      rw [fixed_region_length]
      constructor
      · omega
      · rfl

theorem first_selection_success_small (hashes : Hashes)
    (raw : Bytes) (tail : List Bytes) (outcomes : List Bool)
    (final : State)
    (accepted : run hashes firstSelectionPrefix
      (State.mk (fixedRegion ++ raw :: tail) outcomes 5) = some final) :
    tail.length ≤ 696 := by
  by_contra tooLong
  rw [first_selection_prefix_opcodes] at accepted
  unfold run at accepted
  have firstStep :
      step hashes (.push [0x2e, 0x01])
        (State.mk (fixedRegion ++ raw :: tail) outcomes 5) =
        some (State.mk ([0x2e, 0x01] :: fixedRegion ++ raw :: tail)
          outcomes 5) := by
    unfold step
    simp
  rw [firstStep] at accepted
  simp at accepted
  rw [fixed_region_length] at accepted
  omega

end QSB.FirstAcceptedOrigin
