import QSB.LegacyTxWire
import QSB.SighashAllWireFixture

/-! Generated by analysis/generate_legacy_tx_wire_fixture.py from pinned
baseline Core-probe evidence. It checks one exact app-built raw legacy
transaction, not universal Core-to-Lean parser equivalence. -/
namespace QSB.LegacyTxWireFixture

def fixture : SighashAllWire.TxFields := {
  SighashAllWireFixture.fixture with inputs := [
    (List.replicate 32 (68 : UInt8), (0, ([], 0xfffffffe))),
    (List.replicate 32 (85 : UInt8),
      (1, ([33, 2, 216, 198, 136, 44, 139, 42, 78, 247, 98, 26, 207, 121, 217, 236, 125, 201, 235, 56, 118, 49, 131, 65, 211, 135, 27, 143, 126, 3, 120, 235, 166, 252], 0x80000000)))
  ]
}

theorem fixture_valid : SighashAllWire.valid fixture := by
  norm_num [SighashAllWire.valid, fixture, SighashAllWireFixture.fixture,
    SighashAllWire.inputCodec, OutputCodec.productCodec,
    OutputCodec.fixedBytesCodec, WireIntegers.fixedLECodec,
    OutputCodec.lengthPrefixedBytesCodec, WireOutputs.validOutputs,
    WireIntegers.compactSizeCodec, WireIntegers.nonnegativeAmountCodec]

set_option maxRecDepth 8192 in
theorem fixture_raw_bytes : (LegacyTxWire.encode fixture).map UInt8.toNat =
    [2, 0, 0, 0, 2, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68,
      68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68,
      68, 68, 68, 68, 68, 68, 68, 0, 0, 0, 0, 0, 254, 255, 255,
      255, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85,
      85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85,
      85, 85, 85, 1, 0, 0, 0, 34, 33, 2, 216, 198, 136, 44, 139,
      42, 78, 247, 98, 26, 207, 121, 217, 236, 125, 201, 235, 56, 118, 49,
      131, 65, 211, 135, 27, 143, 126, 3, 120, 235, 166, 252, 0, 0, 0,
      128, 2, 144, 95, 1, 0, 0, 0, 0, 0, 22, 0, 20, 102, 102,
      102, 102, 102, 102, 102, 102, 102, 102, 102, 102, 102, 102, 102, 102, 102,
      102, 102, 102, 232, 3, 0, 0, 0, 0, 0, 0, 1, 81, 135, 214,
      18, 0] := by decide

theorem fixture_decodes :
    LegacyTxWire.decode (LegacyTxWire.encode fixture) = some (fixture, []) :=
  LegacyTxWire.decode_encode fixture fixture_valid

end QSB.LegacyTxWireFixture
