import QSB.LegacySighashWire
import QSB.SighashAllWireFixture

/-! Exact preimage-byte fixtures generated by analysis/generate_legacy_sighash_fixture.py.
These check Lean against the independent Python serializer used on Core 27.2 vectors, not
the full C++ implementation or arbitrary scriptCode construction. -/
namespace QSB.LegacySighashWireFixture

open QSB.LegacySighashWire
open QSB.SighashAllWireFixture

theorem all_branch :
    (sourcePreimage rawFixture 1 [124, 172] 1).map (List.map UInt8.toNat) =
      some [2, 0, 0, 0, 2, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68,
      68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68,
      68, 68, 68, 68, 68, 0, 0, 0, 0, 0, 254, 255, 255, 255, 85, 85,
      85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85,
      85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 1, 0,
      0, 0, 2, 124, 172, 0, 0, 0, 128, 2, 144, 95, 1, 0, 0, 0,
      0, 0, 22, 0, 20, 102, 102, 102, 102, 102, 102, 102, 102, 102, 102, 102,
      102, 102, 102, 102, 102, 102, 102, 102, 102, 232, 3, 0, 0, 0, 0, 0,
      0, 1, 81, 135, 214, 18, 0, 1, 0, 0, 0] := by decide

theorem none_branch :
    (sourcePreimage rawFixture 1 [124, 172] 2).map (List.map UInt8.toNat) =
      some [2, 0, 0, 0, 2, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68,
      68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68,
      68, 68, 68, 68, 68, 0, 0, 0, 0, 0, 0, 0, 0, 0, 85, 85,
      85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85,
      85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 1, 0,
      0, 0, 2, 124, 172, 0, 0, 0, 128, 0, 135, 214, 18, 0, 2, 0,
      0, 0] := by decide

theorem single_branch :
    (sourcePreimage rawFixture 1 [124, 172] 3).map (List.map UInt8.toNat) =
      some [2, 0, 0, 0, 2, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68,
      68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68,
      68, 68, 68, 68, 68, 0, 0, 0, 0, 0, 0, 0, 0, 0, 85, 85,
      85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85,
      85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 1, 0,
      0, 0, 2, 124, 172, 0, 0, 0, 128, 2, 255, 255, 255, 255, 255, 255,
      255, 255, 0, 232, 3, 0, 0, 0, 0, 0, 0, 1, 81, 135, 214, 18,
      0, 3, 0, 0, 0] := by decide

theorem single_anyone :
    (sourcePreimage rawFixture 1 [124, 172] 131).map (List.map UInt8.toNat) =
      some [2, 0, 0, 0, 1, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85,
      85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85,
      85, 85, 85, 85, 85, 1, 0, 0, 0, 2, 124, 172, 0, 0, 0, 128,
      2, 255, 255, 255, 255, 255, 255, 255, 255, 0, 232, 3, 0, 0, 0, 0,
      0, 0, 1, 81, 135, 214, 18, 0, 131, 0, 0, 0] := by decide

theorem unknown_all_anyone :
    (sourcePreimage rawFixture 1 [124, 172] 255).map (List.map UInt8.toNat) =
      some [2, 0, 0, 0, 1, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85,
      85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85,
      85, 85, 85, 85, 85, 1, 0, 0, 0, 2, 124, 172, 0, 0, 0, 128,
      2, 144, 95, 1, 0, 0, 0, 0, 0, 22, 0, 20, 102, 102, 102, 102,
      102, 102, 102, 102, 102, 102, 102, 102, 102, 102, 102, 102, 102, 102, 102, 102,
      232, 3, 0, 0, 0, 0, 0, 0, 1, 81, 135, 214, 18, 0, 255, 0,
      0, 0] := by decide

theorem single_bug :
    sourcePreimage ({ rawFixture with outputs := rawFixture.outputs.take 1 })
      1 [124, 172] 3 = none := by decide

theorem single_bug_raw_digest :
    singleBugDigest.map UInt8.toNat = 1 :: List.replicate 31 0 := by decide

end QSB.LegacySighashWireFixture
