import QSB.LegacySighashWire
import QSB.SighashAllWireFixture

/-! Exact preimage-byte fixtures generated by analysis/generate_legacy_sighash_fixture.py.
These check Lean against the independent Python serializer used on Core 27.2 vectors, not
the full C++ implementation or arbitrary scriptCode construction. -/
namespace QSB.LegacySighashWireFixture

open QSB.LegacySighashWire
open QSB.SighashAllWireFixture

theorem all_branch :
    (sourcePreimage rawFixture 1 [124, 172] 1).map (List.map UInt8.toNat) =
      some [2, 0, 0, 0, 2, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68,
      68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68,
      68, 68, 68, 68, 68, 0, 0, 0, 0, 0, 254, 255, 255, 255, 85, 85,
      85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85,
      85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 1, 0,
      0, 0, 2, 124, 172, 0, 0, 0, 128, 2, 144, 95, 1, 0, 0, 0,
      0, 0, 22, 0, 20, 102, 102, 102, 102, 102, 102, 102, 102, 102, 102, 102,
      102, 102, 102, 102, 102, 102, 102, 102, 102, 232, 3, 0, 0, 0, 0, 0,
      0, 1, 81, 135, 214, 18, 0, 1, 0, 0, 0] := by decide

theorem none_branch :
    (sourcePreimage rawFixture 1 [124, 172] 2).map (List.map UInt8.toNat) =
      some [2, 0, 0, 0, 2, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68,
      68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68,
      68, 68, 68, 68, 68, 0, 0, 0, 0, 0, 0, 0, 0, 0, 85, 85,
      85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85,
      85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 1, 0,
      0, 0, 2, 124, 172, 0, 0, 0, 128, 0, 135, 214, 18, 0, 2, 0,
      0, 0] := by decide

theorem single_branch :
    (sourcePreimage rawFixture 1 [124, 172] 3).map (List.map UInt8.toNat) =
      some [2, 0, 0, 0, 2, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68,
      68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68,
      68, 68, 68, 68, 68, 0, 0, 0, 0, 0, 0, 0, 0, 0, 85, 85,
      85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85,
      85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 1, 0,
      0, 0, 2, 124, 172, 0, 0, 0, 128, 2, 255, 255, 255, 255, 255, 255,
      255, 255, 0, 232, 3, 0, 0, 0, 0, 0, 0, 1, 81, 135, 214, 18,
      0, 3, 0, 0, 0] := by decide

theorem single_anyone :
    (sourcePreimage rawFixture 1 [124, 172] 131).map (List.map UInt8.toNat) =
      some [2, 0, 0, 0, 1, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85,
      85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85,
      85, 85, 85, 85, 85, 1, 0, 0, 0, 2, 124, 172, 0, 0, 0, 128,
      2, 255, 255, 255, 255, 255, 255, 255, 255, 0, 232, 3, 0, 0, 0, 0,
      0, 0, 1, 81, 135, 214, 18, 0, 131, 0, 0, 0] := by decide

theorem unknown_all_anyone :
    (sourcePreimage rawFixture 1 [124, 172] 255).map (List.map UInt8.toNat) =
      some [2, 0, 0, 0, 1, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85,
      85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85,
      85, 85, 85, 85, 85, 1, 0, 0, 0, 2, 124, 172, 0, 0, 0, 128,
      2, 144, 95, 1, 0, 0, 0, 0, 0, 22, 0, 20, 102, 102, 102, 102,
      102, 102, 102, 102, 102, 102, 102, 102, 102, 102, 102, 102, 102, 102, 102, 102,
      232, 3, 0, 0, 0, 0, 0, 0, 1, 81, 135, 214, 18, 0, 255, 0,
      0, 0] := by decide

theorem single_bug :
    sourcePreimage ({ rawFixture with outputs := rawFixture.outputs.take 1 })
      1 [124, 172] 3 = none := by decide

theorem single_bug_raw_digest :
    singleBugDigest.map UInt8.toNat = 1 :: List.replicate 31 0 := by decide

/-- A source-wire counterexample to whole-output binding by an in-range
SIGHASH_SINGLE signature. Input 1's selected output is unchanged, while output
0 changes by one satoshi. The matched preimage says nothing about ECDSA
validity or acceptance of the complete QSB lock. -/
def changedFirstOutput : SighashAllWire.TxFields :=
  { rawFixture with outputs :=
      { value := 90001, script := [0, 20] ++
          List.replicate 20 (102 : UInt8) } :: rawFixture.outputs.drop 1 }

theorem changed_first_output_same_single_preimage :
    changedFirstOutput.outputs ≠ rawFixture.outputs ∧
    sourcePreimage changedFirstOutput 1 [124, 172] 3 =
      sourcePreimage rawFixture 1 [124, 172] 3 := by
  constructor
  · decide
  · exact single_same_selected_output_preimage rawFixture 1 [124, 172]
      3 changedFirstOutput.outputs (by decide) (by decide) (by decide)
      (by decide) (by decide)

theorem changed_first_output_changes_all_preimage :
    sourcePreimage changedFirstOutput 1 [124, 172] 1 ≠
      sourcePreimage rawFixture 1 [124, 172] 1 := by decide

end QSB.LegacySighashWireFixture
