import QSB.SighashAllWire

/-! Generated by analysis/generate_sighash_wire_fixture.py from the pinned
baseline evidence. The equality checks a source-shaped Lean serializer against
the app-built preimage used in the native Core probe. This is one fixture,
not a universal C++/Lean refinement theorem. -/
namespace QSB.SighashAllWireFixture

open QSB.SighashAllWire

def fixture : TxFields := {
  version := 2
  inputs := [
    (List.replicate 32 (68 : UInt8), (0, ([], 0xfffffffe))),
    (List.replicate 32 (85 : UInt8), (1, ([124, 172], 0x80000000)))
  ]
  outputs := [
    { value := 90000, script := [0, 20] ++ List.replicate 20 (102 : UInt8) },
    { value := 1000, script := [81] }
  ]
  locktime := 1234567
}

theorem fixture_valid : valid fixture := by
  norm_num [valid, fixture, inputCodec, OutputCodec.productCodec,
    OutputCodec.fixedBytesCodec, WireIntegers.fixedLECodec,
    OutputCodec.lengthPrefixedBytesCodec, WireOutputs.validOutputs,
    WireIntegers.compactSizeCodec, WireIntegers.nonnegativeAmountCodec]

theorem fixture_preimage_bytes : (encode fixture).map UInt8.toNat =
    [2, 0, 0, 0, 2, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68,
      68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68,
      68, 68, 68, 68, 68, 68, 68, 0, 0, 0, 0, 0, 254, 255, 255,
      255, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85,
      85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85,
      85, 85, 85, 1, 0, 0, 0, 2, 124, 172, 0, 0, 0, 128, 2,
      144, 95, 1, 0, 0, 0, 0, 0, 22, 0, 20, 102, 102, 102, 102,
      102, 102, 102, 102, 102, 102, 102, 102, 102, 102, 102, 102, 102, 102, 102,
      102, 232, 3, 0, 0, 0, 0, 0, 0, 1, 81, 135, 214, 18, 0,
      1, 0, 0, 0] := by decide

theorem fixture_outputs_parsed : decodeOutputs (encode fixture) =
    some fixture.outputs :=
  decodeOutputs_encode fixture fixture_valid

/-- Original scriptSig bytes are irrelevant to the BASE/ALL preimage:
Core-shaped preparation blanks the other input and substitutes scriptCode
for the signed input. This checks that preparation against the same pinned
139-byte fixture, without asserting a universal C++ refinement. -/
def rawFixture : TxFields := { fixture with inputs := [
  (List.replicate 32 (68 : UInt8), (0, ([81], 0xfffffffe))),
  (List.replicate 32 (85 : UInt8), (1, ([81, 81], 0x80000000)))
] }

theorem raw_fixture_preimage :
    sourceAllPreimage rawFixture 1 [124, 172] = encode fixture := by decide

end QSB.SighashAllWireFixture
