"""Generate a disposable byte witness for the pinned Config A lock model.

This checks only byte-stack and hash-comparison behavior. Signature checks in
ByteMachine still consume supplied Boolean outcomes, not ECDSA verification.
"""
import argparse
import hashlib
import json
import random
import sys
from pathlib import Path


def lean_bytes(value):
    return "[" + ", ".join(f"0x{b:02x}" for b in value) + "]"


def script_num(value):
    if value == 0:
        return b""
    assert 0 < value < 2**31
    digits = value.to_bytes((value.bit_length() + 7) // 8, "little")
    return digits + (b"\0" if digits[-1] & 0x80 else b"")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--app-root", type=Path, required=True)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    root = Path(__file__).resolve().parents[1]
    sys.path.insert(0, str(args.app_root / "worker/cpu"))
    import bitcoin_tx as bt

    builder = bt.QSBScriptBuilder(150, 8, 1, 7, 2, hash_mode="sha256")
    rng = random.Random("QSB security analysis: PUBLIC DISPOSABLE TEST MATERIAL")
    old = bt.os.urandom
    try:
        bt.os.urandom = rng.randbytes
        builder.generate_keys()
    finally:
        bt.os.urandom = old
    subsets = {0: list(range(9)), 1: list(range(9))}
    indices = builder.compute_witness_indices(subsets)
    witness = []
    openings = []
    for ri in (1, 0):
        for role in ("puzzle", "nonce"):
            witness.append(hashlib.sha256(f"round-{ri}-{role}".encode()).digest())
        witness.extend(builder.dummy_sigs[ri][j] for j in range(8, -1, -1))
        count = 8 if ri == 0 else 7
        witness.extend(builder.hors_secrets[ri][j] for j in range(count - 1, -1, -1))
        openings.extend((builder.hors_secrets[ri][j], builder.hors_commitments[ri][j])
                        for j in range(count))
        witness.extend(script_num(value) for value in reversed(indices[ri]))
    for role in ("puzzle", "nonce"):
        witness.append(hashlib.sha256(f"pin-{role}".encode()).digest())
    witness.reverse()
    assert len({value for value, _ in openings}) == 15

    h160 = "\n  ".join(
        f"if x = {lean_bytes(value)} then ⟨{lean_bytes(commitment)}, by decide⟩ else"
        for value, commitment in openings)
    witness_text = ",\n  ".join(lean_bytes(value) for value in witness)
    source_hash = hashlib.sha256((args.app_root / "worker/cpu/bitcoin_tx.py").read_bytes()).hexdigest()
    assert source_hash == json.loads((root / "evidence/layout-map.json").read_text())["builder_sha256"]
    out = f"""import QSB.ByteTrace

/-!
GENERATED by analysis/generate_byte_witness.py from disposable public test data.
This is an execution fixture for ByteMachine, whose signature outcomes are
externally supplied. It is not a valid QSB spend or a cryptographic proof.
bitcoin_tx.py SHA-256: {source_hash}
-/
namespace QSB.ByteWitness
open ByteMachine
set_option maxRecDepth 20000
set_option maxHeartbeats 10000000

def witness : List Bytes := [
  {witness_text}
]

def h160 (x : Bytes) : {{ value : Bytes // value.length = 20 }} :=
  {h160}
  ⟨List.replicate 20 0, by decide⟩

def hashes : Hashes := {{
  h160 := fun x => (h160 x).val,
  h256 := fun _ => List.replicate 32 0,
  h160_width := fun x => (h160 x).property,
  h256_width := by intro; decide
}}

theorem witness_length : witness.length = {len(witness)} := by decide

def execute (round1 round2 : Bool) : Option State :=
  run hashes ByteLayout.program
    (State.mk witness [true, true, true, round1, true, round2] 0)

theorem canonical_byte_run :
    (execute false true).map
      (fun s => (finalTruth s, s.ops, s.stack.length, s.outcomes.length)) =
      some (true, 201, 569, 0) := by decide

theorem first_round_boolean_ignored (first final : Bool) :
    (execute first final).map finalTruth = some final := by
  cases first <;> cases final <;> decide

theorem all_fifteen_comparisons_reached :
    (ByteTrace.runCompared hashes ByteLayout.program
      (State.mk witness [true, true, true, false, true, true] 0)).map
      (fun result => result.2.length) = some 15 := by decide

end QSB.ByteWitness
"""
    path = root / "QSB/ByteWitness.lean"
    if args.check:
        assert path.read_text() == out, "Generated byte witness drift"
    else:
        path.write_text(out)
    print(f"{'Checked' if args.check else 'Generated'} {len(witness)} witness cells and {len(openings)} openings")


if __name__ == "__main__":
    main()
