"""Translate the actual Config A opcode skeleton into a Lean symbolic fixture.

All source bytes are generated from public, disposable deterministic test data.
The generated file records the exact source and script identities. Signature
outcomes remain assumptions of the structural trace, not solved hash puzzles.
"""
import argparse
import hashlib
import json
import random
import sys
from pathlib import Path

def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--app-root", type=Path, required=True)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    root = Path(__file__).resolve().parents[1]
    sys.path.insert(0, str(args.app_root / "worker/cpu"))
    import bitcoin_tx as bt
    import secp256k1 as ec
    builder = bt.QSBScriptBuilder(150, 8, 1, 7, 2, hash_mode="sha256")
    rng = random.Random("QSB security analysis: PUBLIC DISPOSABLE TEST MATERIAL")
    old = bt.os.urandom
    try:
        bt.os.urandom = rng.randbytes
        builder.generate_keys()
    finally:
        bt.os.urandom = old
    def nonce_sig(label):
        k = int.from_bytes(hashlib.sha256(label + b"_nonce").digest(), "big") % ec.N
        r = ec.point_mul(k, ec.G)[0] % ec.N
        s = max(1, int.from_bytes(hashlib.sha256(label + b"_s").digest()[:16], "big") % (ec.N // 2))
        return ec.encode_der_sig(r, s, sighash=1)
    nonces = [nonce_sig(x) for x in (b"qsb_pin", b"qsb_r0", b"qsb_r1")]
    script = builder.build_full_script(*nonces)
    labels = {}
    for ri in range(2):
        for i in range(150):
            labels[builder.hors_commitments[ri][i]] = f".hash160 (.atom {ri*150+i})"
            labels[builder.dummy_sigs[ri][i]] = f".atom {1000+ri*150+i}"
    for j, sig in enumerate(nonces):
        labels[sig] = f".atom {2000+j}"
    assert len(labels) == 603
    names = {bt.OP_DUP: "dup", bt.OP_OVER: "over", bt.OP_SWAP: "swap",
             bt.OP_ROLL: "roll", bt.OP_MIN: "min", bt.OP_ADD: "add",
             bt.OP_HASH160: "hash160", bt.OP_SHA256_OP: "sha256",
             bt.OP_EQUALVERIFY: "equalverify", bt.OP_CHECKSIGVERIFY: "checksigverify",
             bt.OP_CHECKMULTISIG: "checkmultisig"}
    instructions = []
    offsets = []
    i = 0
    while i < len(script):
        start, op = i, script[i]
        i += 1
        if op == 0:
            term = ".push (.num 0)"
        elif 0x51 <= op <= 0x60:
            term = f".push (.num {op - 0x50})"
        elif 1 <= op <= 75:
            data = script[i:i+op]
            i += op
            if data in labels:
                term = f".push ({labels[data]})"
            else:
                assert len(data) <= 4
                magnitude = int.from_bytes(data, "little")
                assert not data[-1] & 0x80
                term = f".push (.num {magnitude})"
        else:
            term = "." + names[op]
        instructions.append(term)
        offsets.append({"instruction": len(instructions)-1, "byte_offset": start, "term": term})
    subsets = {0: list(range(9)), 1: list(range(9))}
    iv = builder.compute_witness_indices(subsets)
    witness = []
    for ri in (1, 0):
        witness += [f".atom {3000+100*ri}", f".atom {3001+100*ri}"]
        witness += [f".atom {3010+100*ri+j}" for j in range(8, -1, -1)]
        witness += [f".atom {ri*150+j}" for j in range((8 if ri == 0 else 7)-1, -1, -1)]
        witness += [f".num {v}" for v in reversed(iv[ri])]
    witness += [".atom 4000", ".atom 4001"]
    witness.reverse()  # Lean machine is top-first; source assembly is bottom-first.
    source_hash = hashlib.sha256((args.app_root / "worker/cpu/bitcoin_tx.py").read_bytes()).hexdigest()
    text = """import QSB.StackMachine

/-!
GENERATED by analysis/generate_layout.py. Do not edit opcode literals by hand.
Exact Config A opcode skeleton from the pinned source. Hash applications are
symbolic; outcomes of the four CHECKSIGVERIFY and two CHECKMULTISIG operations
are explicit. This proves stack/control behavior conditional on those outcomes,
not cryptographic realizability or a real-lock unauthorized transaction.
SOURCE_HASH
SCRIPT_HASH
-/
namespace QSB.Layout
open StackMachine
set_option maxRecDepth 20000
set_option maxHeartbeats 10000000

def program : List Op := [
INSTRUCTIONS
]

def witness : List Cell := [
WITNESS
]

/-- In this deliberately malformed witness, the first signed index is 152 and
an attacker-controlled 20-byte cell is inserted just below the initial indices.
The first selection's OP_MIN/OP_ROLL can therefore reach beyond the intended
commitment pool. This is a local reachability example, not an accepted spend. -/
def externalCommitmentProbe : List Cell :=
  (witness.set 2 (.num 152)).insertIdx 3 (.hash160 (.atom 9999))

theorem first_selection_can_reach_external_cell :
    (run (program.take 316)
      (State.mk externalCommitmentProbe [true, true, true, false, true, true] 0)).bind
      (fun s => s.stack.head?) = some (.hash160 (.atom 9999)) := by decide

theorem external_probe_not_full_acceptance :
    (run program
      (State.mk externalCommitmentProbe [true, true, true, false, true, true] 0)).isSome =
      false := by decide

/-- If the external marker is chosen to match the next rolled preimage, the
first HASH160 comparison succeeds. The next index parse fails in this particular
malformed witness. Neither result is a complete-lock forgery. -/
def matchedExternalProbe : List Cell :=
  (witness.set 2 (.num 152)).insertIdx 3 (.hash160 (.num 10))

theorem matched_external_passes_first_comparison :
    (run (program.take 320)
      (State.mk matchedExternalProbe [true, true, true, false, true, true] 0)).isSome =
      true := by decide

theorem matched_external_fails_second_index :
    (run (program.take 324)
      (State.mk matchedExternalProbe [true, true, true, false, true, true] 0)).isSome =
      true ∧
    (run (program.take 325)
      (State.mk matchedExternalProbe [true, true, true, false, true, true] 0)).isSome =
      false := by decide

/-- The last final-round bonus index can reach a locking-script HORS
commitment rather than a dummy signature. Symbolic CHECKMULTISIG success is an
input here; a real commitment would also need valid DER and an appropriate key.
The separate altered-lock Core probe tests that condition. -/
def lastBonusOvershootProbe : List Cell := witness.set 38 (.num 152)

theorem last_bonus_overshoot_selects_commitment :
    (run (program.take 850)
      (State.mk lastBonusOvershootProbe [true, true, true, false, true, true] 0)).bind
      (fun s => s.stack.head?) = some (.hash160 (.atom 157)) := by decide

theorem last_bonus_overshoot_symbolic_trace_accepts :
    (run program
      (State.mk lastBonusOvershootProbe [true, true, true, false, true, true] 0)).map
      (fun s => finalTruth s && s.outcomes.isEmpty) = some true := by decide

def execute (round1 round2 : Bool) : Option State :=
  run program (State.mk witness [true, true, true, round1, true, round2] 0)

def accepted (round1 round2 : Bool) : Bool :=
  match execute round1 round2 with
  | some s => finalTruth s && s.outcomes.isEmpty
  | none => false

theorem first_multisig_false_still_accepts : accepted false true = true := by decide
theorem both_multisigs_true_accept : accepted true true = true := by decide
theorem final_multisig_false_rejects (first : Bool) : accepted first false = false := by
  cases first <;> decide

theorem first_multisig_result_irrelevant (first final : Bool) :
    accepted first final = final := by
  cases first <;> cases final <;> decide

theorem accepted_trace_operation_count :
    (execute false true).map State.ops = some 201 := by decide

theorem accepted_trace_stack_size :
    (execute false true).map (fun s => s.stack.length) = some 569 := by decide

theorem first_result_retained_below_top :
    (execute false true).bind (fun s => s.stack[285]?) = some (.num 0) := by decide

end QSB.Layout
"""
    text = text.replace("SOURCE_HASH", f"bitcoin_tx.py SHA-256: {source_hash}")
    text = text.replace("SCRIPT_HASH", f"Synthetic exact lock SHA-256: {hashlib.sha256(script).hexdigest()}")
    text = text.replace("INSTRUCTIONS", "  " + ",\n  ".join(instructions))
    text = text.replace("WITNESS", "  " + ",\n  ".join(witness))
    path = root / "QSB/Layout.lean"
    report = {"builder_sha256": source_hash, "script_sha256": hashlib.sha256(script).hexdigest(),
              "script_bytes": len(script), "instructions": offsets, "witness_cells": len(witness)}
    output = json.dumps(report, indent=2) + "\n"
    if args.check:
        assert path.read_text() == text, "Generated Lean fixture drift"
        assert (root / "evidence/layout-map.json").read_text() == output, "Generated map drift"
    else:
        path.write_text(text)
        (root / "evidence/layout-map.json").write_text(output)
    print(f"{'Checked' if args.check else 'Generated'} {len(instructions)} instructions from {len(script)} bytes")

if __name__ == "__main__":
    main()
