"""Check a Lean raw-transaction fixture against pinned Core probe evidence.

The expected bytes come from the app-built transaction accepted by the
pinned Core adapter in the baseline ALL-commitment experiment. This is one
cross-language example, not universal equivalence with Core's parser.
"""

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]


def main() -> None:
    cases = json.loads((ROOT / "evidence/all-sighash-commitments.json").read_text())["cases"]
    baseline = cases[0]
    assert baseline["name"] == "baseline" and baseline["old_key_accepted"]
    public_key = bytes.fromhex(baseline["fresh_pubkey_hex"])
    assert len(public_key) == 33
    script_sig = bytes([33]) + public_key
    expected_raw = (
        (2).to_bytes(4, "little") + bytes([2])
        + bytes([68]) * 32 + (0).to_bytes(4, "little")
        + bytes([0]) + (0xFFFFFFFE).to_bytes(4, "little")
        + bytes([85]) * 32 + (1).to_bytes(4, "little")
        + bytes([len(script_sig)]) + script_sig
        + (0x80000000).to_bytes(4, "little")
        + bytes([2])
        + (90000).to_bytes(8, "little")
        + bytes([22, 0, 20]) + bytes([102]) * 20
        + (1000).to_bytes(8, "little") + bytes([1, 81])
        + (1234567).to_bytes(4, "little")
    )
    assert expected_raw.hex() == baseline["old_key_raw_tx_hex"]
    assert expected_raw.hex() == baseline["fresh_key_raw_tx_hex"]
    key_list = ", ".join(str(byte) for byte in public_key)
    values = [str(byte) for byte in expected_raw]
    raw_list = ",\n      ".join(
        ", ".join(values[i:i + 15]) for i in range(0, len(values), 15)
    )
    source = f"""import QSB.LegacyTxWire
import QSB.SighashAllWireFixture

/-! Generated by analysis/generate_legacy_tx_wire_fixture.py from pinned
baseline Core-probe evidence. It checks one exact app-built raw legacy
transaction, not universal Core-to-Lean parser equivalence. -/
namespace QSB.LegacyTxWireFixture

def fixture : SighashAllWire.TxFields := {{
  SighashAllWireFixture.fixture with inputs := [
    (List.replicate 32 (68 : UInt8), (0, ([], 0xfffffffe))),
    (List.replicate 32 (85 : UInt8),
      (1, ([33, {key_list}], 0x80000000)))
  ]
}}

theorem fixture_valid : SighashAllWire.valid fixture := by
  norm_num [SighashAllWire.valid, fixture, SighashAllWireFixture.fixture,
    SighashAllWire.inputCodec, OutputCodec.productCodec,
    OutputCodec.fixedBytesCodec, WireIntegers.fixedLECodec,
    OutputCodec.lengthPrefixedBytesCodec, WireOutputs.validOutputs,
    WireIntegers.compactSizeCodec, WireIntegers.nonnegativeAmountCodec]

set_option maxRecDepth 8192 in
theorem fixture_raw_bytes : (LegacyTxWire.encode fixture).map UInt8.toNat =
    [{raw_list}] := by decide

theorem fixture_decodes :
    LegacyTxWire.decode (LegacyTxWire.encode fixture) = some (fixture, []) :=
  LegacyTxWire.decode_encode fixture fixture_valid

end QSB.LegacyTxWireFixture
"""
    destination = ROOT / "QSB/LegacyTxWireFixture.lean"
    destination.write_text(source)
    print(f"Generated {destination} from {len(expected_raw)} accepted transaction bytes")


if __name__ == "__main__":
    main()
