"""Generate exact Lean byte fixtures from the independent Core-vector serializer.

The raw transaction fields mirror SighashAllWireFixture.rawFixture. The
serializer was separately checked against the pinned Core 27.2 corpus; these
examples connect that Python path to Lean without claiming universal C++
refinement. Rerun after changing either source-shaped model.
"""

from pathlib import Path

from check_core_sighash_vectors import source_shaped_preimage


ROOT = Path(__file__).resolve().parents[1]
FIELDS = (
    2,
    [(b"\x44" * 32, 0, b"\x51", 0xFFFFFFFE),
     (b"\x55" * 32, 1, b"\x51\x51", 0x80000000)],
    [((90000).to_bytes(8, "little"), b"\x00\x14" + b"\x66" * 20),
     ((1000).to_bytes(8, "little"), b"\x51")],
    1234567,
)


def row(name: str, fields, hash_type: int) -> str:
    preimage = source_shaped_preimage(fields, 1, b"\x7c\xac", hash_type)
    assert preimage is not None
    items = [str(byte) for byte in preimage]
    lines = [", ".join(items[i:i + 16]) for i in range(0, len(items), 16)]
    literal = ",\n      ".join(lines)
    return (f"theorem {name} :\n"
            f"    (sourcePreimage rawFixture 1 [124, 172] {hash_type}).map "
            f"(List.map UInt8.toNat) =\n"
            f"      some [{literal}] := by decide\n")


def main() -> None:
    out = [
        "import QSB.LegacySighashWire\n",
        "import QSB.SighashAllWireFixture\n\n",
        "/-! Exact preimage-byte fixtures generated by "
        "analysis/generate_legacy_sighash_fixture.py.\n"
        "These check Lean against the independent Python serializer used on "
        "Core 27.2 vectors, not\n"
        "the full C++ implementation or arbitrary scriptCode construction. -/\n",
        "namespace QSB.LegacySighashWireFixture\n\n",
        "open QSB.LegacySighashWire\n",
        "open QSB.SighashAllWireFixture\n\n",
    ]
    for name, hash_type in [
        ("all_branch", 1), ("none_branch", 2), ("single_branch", 3),
        ("single_anyone", 0x83), ("unknown_all_anyone", 0xFF),
    ]:
        out.append(row(name, FIELDS, hash_type))
        out.append("\n")
    out.append("theorem single_bug :\n"
               "    sourcePreimage ({ rawFixture with outputs := rawFixture.outputs.take 1 })\n"
               "      1 [124, 172] 3 = none := by decide\n\n")
    out.append("theorem single_bug_raw_digest :\n"
               "    singleBugDigest.map UInt8.toNat = 1 :: List.replicate 31 0 := by decide\n\n")
    out.append("end QSB.LegacySighashWireFixture\n")
    (ROOT / "QSB/LegacySighashWireFixture.lean").write_text("".join(out))


if __name__ == "__main__":
    main()
