"""Generate the Lean legacy-ALL wire fixture from pinned native-probe evidence.

The fixture transaction fields mirror check_all_sighash_commitments.py. The
expected preimage bytes come from the app's independently assembled serializer
and were accepted through the pinned Core adapter with a recovered key.
"""

import hashlib
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]


def main() -> None:
    report = json.loads((ROOT / "evidence/all-sighash-commitments.json").read_text())
    baseline = report["cases"][0]
    assert baseline["name"] == "baseline"
    assert baseline["old_key_accepted"] and baseline["fresh_key_accepted"]
    preimage = bytes.fromhex(baseline["preimage_hex"])
    digest = hashlib.sha256(hashlib.sha256(preimage).digest()).hexdigest()
    assert digest == baseline["digest_sha256d_hex"]
    values = [str(byte) for byte in preimage]
    rows = [", ".join(values[i:i + 15]) for i in range(0, len(values), 15)]
    byte_list = ",\n      ".join(rows)
    source = f"""import QSB.SighashAllWire

/-! Generated by analysis/generate_sighash_wire_fixture.py from the pinned
baseline evidence. The equality checks a source-shaped Lean serializer against
the app-built preimage used in the native Core probe. This is one fixture,
not a universal C++/Lean refinement theorem. -/
namespace QSB.SighashAllWireFixture

open QSB.SighashAllWire

def fixture : TxFields := {{
  version := 2
  inputs := [
    (List.replicate 32 (68 : UInt8), (0, ([], 0xfffffffe))),
    (List.replicate 32 (85 : UInt8), (1, ([124, 172], 0x80000000)))
  ]
  outputs := [
    {{ value := 90000, script := [0, 20] ++ List.replicate 20 (102 : UInt8) }},
    {{ value := 1000, script := [81] }}
  ]
  locktime := 1234567
}}

theorem fixture_valid : valid fixture := by
  norm_num [valid, fixture, inputCodec, OutputCodec.productCodec,
    OutputCodec.fixedBytesCodec, WireIntegers.fixedLECodec,
    OutputCodec.lengthPrefixedBytesCodec, WireOutputs.validOutputs,
    WireIntegers.compactSizeCodec, WireIntegers.nonnegativeAmountCodec]

theorem fixture_preimage_bytes : (encode fixture).map UInt8.toNat =
    [{byte_list}] := by decide

theorem fixture_outputs_parsed : decodeOutputs (encode fixture) =
    some fixture.outputs :=
  decodeOutputs_encode fixture fixture_valid

/-- Original scriptSig bytes are irrelevant to the BASE/ALL preimage:
Core-shaped preparation blanks the other input and substitutes scriptCode
for the signed input. This checks that preparation against the same pinned
139-byte fixture, without asserting a universal C++ refinement. -/
def rawFixture : TxFields := {{ fixture with inputs := [
  (List.replicate 32 (68 : UInt8), (0, ([81], 0xfffffffe))),
  (List.replicate 32 (85 : UInt8), (1, ([81, 81], 0x80000000)))
] }}

theorem raw_fixture_preimage :
    sourceAllPreimage rawFixture 1 [124, 172] = encode fixture := by decide

end QSB.SighashAllWireFixture
"""
    destination = ROOT / "QSB/SighashAllWireFixture.lean"
    destination.write_text(source)
    print(f"Generated {destination} from {len(preimage)} pinned preimage bytes")


if __name__ == "__main__":
    main()
