"""Generate byte-push Lean opcodes from the pinned Config A builder.

The fixture keeps literal push bytes instead of the tagged cells used by
generate_layout.py. Hashes and signature checks remain external to the Lean
byte interpreter. The generator cross-checks the existing exact script hash.
"""
import argparse
import hashlib
import json
import random
import sys
from pathlib import Path


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--app-root", type=Path, required=True)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    root = Path(__file__).resolve().parents[1]
    sys.path.insert(0, str(args.app_root / "worker/cpu"))
    import bitcoin_tx as bt
    import secp256k1 as ec

    builder = bt.QSBScriptBuilder(150, 8, 1, 7, 2, hash_mode="sha256")
    rng = random.Random("QSB security analysis: PUBLIC DISPOSABLE TEST MATERIAL")
    old = bt.os.urandom
    try:
        bt.os.urandom = rng.randbytes
        builder.generate_keys()
    finally:
        bt.os.urandom = old

    def nonce_sig(label):
        k = int.from_bytes(hashlib.sha256(label + b"_nonce").digest(), "big") % ec.N
        r = ec.point_mul(k, ec.G)[0] % ec.N
        s = max(1, int.from_bytes(hashlib.sha256(label + b"_s").digest()[:16], "big") % (ec.N // 2))
        return ec.encode_der_sig(r, s, sighash=1)

    script = builder.build_full_script(*(nonce_sig(x) for x in
        (b"qsb_pin", b"qsb_r0", b"qsb_r1")))
    source_hash = hashlib.sha256((args.app_root / "worker/cpu/bitcoin_tx.py").read_bytes()).hexdigest()
    script_hash = hashlib.sha256(script).hexdigest()
    layout = json.loads((root / "evidence/layout-map.json").read_text())
    assert source_hash == layout["builder_sha256"]
    assert script_hash == layout["script_sha256"]

    names = {bt.OP_DUP: "dup", bt.OP_OVER: "over", bt.OP_SWAP: "swap",
             bt.OP_ROLL: "roll", bt.OP_MIN: "min", bt.OP_ADD: "add",
             bt.OP_HASH160: "hash160", bt.OP_SHA256_OP: "sha256",
             bt.OP_EQUALVERIFY: "equalverify", bt.OP_CHECKSIGVERIFY: "checksigverify",
             bt.OP_CHECKMULTISIG: "checkmultisig"}
    instructions = []
    encoded_chunks = []
    offsets = []
    i = 0
    while i < len(script):
        start, op = i, script[i]
        i += 1
        if op == 0:
            data = b""
        elif 0x51 <= op <= 0x60:
            data = bytes([op - 0x50])
        elif 1 <= op <= 75:
            data = script[i:i + op]
            assert len(data) == op
            i += op
        else:
            data = None
        if data is not None:
            term = ".push [" + ", ".join(f"0x{b:02x}" for b in data) + "]"
        else:
            term = "." + names[op]
        instructions.append(term)
        encoded_chunks.append(script[start:i])
        offsets.append({"instruction": len(instructions) - 1,
                        "byte_offset": start, "term": term})

    assert len(instructions) == 880
    assert b"".join(encoded_chunks) == script
    comparison_positions = [i - 1 for i, op in enumerate(instructions)
                            if op == ".equalverify"]
    assert len(comparison_positions) == 15
    assert all(instructions[i] == ".hash160" for i in comparison_positions)
    instruction_text = ",\n  ".join(instructions)
    comparison_text = ", ".join(map(str, comparison_positions))
    out = f"""import QSB.ByteMachine

/-!
GENERATED by analysis/generate_byte_layout.py. Do not edit opcode literals.
Literal push bytes from the pinned Config A locking script.
bitcoin_tx.py SHA-256: {source_hash}
Synthetic exact lock SHA-256: {script_hash}
The hash functions and signature outcomes are supplied by ByteMachine.
-/
namespace QSB.ByteLayout
open ByteMachine
set_option maxRecDepth 20000
set_option maxHeartbeats 10000000

def program : List Op := [
  {instruction_text}
]

theorem program_length : program.length = 880 := by decide
theorem final_opcode_is_checkmultisig :
    program.getLast? = some .checkmultisig := by decide
theorem fifteen_hors_comparisons :
    (program.filter (· == .equalverify)).length = 15 := by decide
theorem comparisons_follow_hash160 :
    (program.zip (program.drop 1)).all
      (fun pair => if pair.2 == .equalverify then pair.1 == .hash160 else true) = true := by
  decide

def hashComparisonPositions : List Nat := [{comparison_text}]

theorem hash_comparison_positions_valid :
    hashComparisonPositions.length = 15 ∧
    hashComparisonPositions.all (fun i =>
      program[i]? == some .hash160 && program[i + 1]? == some .equalverify) = true := by
  decide

end QSB.ByteLayout
"""
    encoded_text = ",\n  ".join(
        "[" + ", ".join(f"0x{b:02x}" for b in chunk) + "]"
        for chunk in encoded_chunks)
    encoded_out = f"""import QSB.ByteMachine

/-!
GENERATED by analysis/generate_byte_layout.py. Do not edit encoded chunks.
Serialized opcode bytes of the pinned disposable Config A lock.
bitcoin_tx.py SHA-256: {source_hash}
Synthetic exact lock SHA-256: {script_hash}
-/
namespace QSB.EncodedLayout
open ByteMachine
set_option maxRecDepth 50000
set_option maxHeartbeats 10000000

def chunks : List Bytes := [
  {encoded_text}
]

theorem chunks_length : chunks.length = 880 := by decide
theorem script_length : chunks.flatten.length = 9923 := by decide

end QSB.EncodedLayout
"""
    path = root / "QSB/ByteLayout.lean"
    encoded_path = root / "QSB/EncodedLayout.lean"
    map_path = root / "evidence/byte-layout-map.json"
    report = {"builder_sha256": source_hash, "script_sha256": script_hash,
              "script_bytes": len(script), "instructions": offsets}
    report_text = json.dumps(report, indent=2) + "\n"
    if args.check:
        assert path.read_text() == out, "Generated byte Lean fixture drift"
        assert encoded_path.read_text() == encoded_out, "Generated encoded Lean fixture drift"
        assert map_path.read_text() == report_text, "Generated byte map drift"
    else:
        path.write_text(out)
        encoded_path.write_text(encoded_out)
        map_path.write_text(report_text)
    print(f"{'Checked' if args.check else 'Generated'} {len(instructions)} byte instructions from {len(script)} bytes")


if __name__ == "__main__":
    main()
