import QSB.Disclosure
import QSB.Extraction
import QSB.Probability
import QSB.Nonce
import QSB.Parameters
import QSB.Selection
import QSB.Layout
import QSB.Bonus
import QSB.ByteIndex
import QSB.Multisig
import QSB.KeyRolls
import QSB.ByteTrace
import QSB.ByteWitness
import QSB.FirstOvershoot
import QSB.FirstIndexMap
import QSB.Attack
import QSB.Game
import QSB.Reduction

#print axioms QSB.openings_fresh_or_covered
#print axioms QSB.one_disclosure_fresh_or_same
#print axioms QSB.insufficient_disclosure_requires_fresh
#print axioms QSB.covered_after_more_disclosure
#print axioms QSB.extracted_round_fresh_or_puzzle
#print axioms QSB.event_bound
#print axioms QSB.event_bound_with_gap
#print axioms QSB.event_bound_with_key_cases
#print axioms QSB.finite_target_union_bound
#print axioms QSB.der20_setup_union_bound
#print axioms QSB.public_scalar_satisfies
#print axioms QSB.fixed_recovery_point_message_unique
#print axioms QSB.fixed_message_key_unique
#print axioms QSB.public_recovery_for_any_message
#print axioms QSB.common_key_requires_equal_recoveries
#print axioms QSB.equal_recoveries_give_common_key
#print axioms QSB.configA_round1_bonus_choices
#print axioms QSB.configA_round2_bonus_choices
#print axioms QSB.configA_pool_choices
#print axioms QSB.coveredFinalChoices_zero
#print axioms QSB.coveredFinalChoices_mono
#print axioms QSB.coveredFinalChoices_one_disclosure
#print axioms QSB.coveredFinalChoices_two_disjoint_disclosures
#print axioms QSB.coveredFinalChoices_three_disjoint_disclosures
#print axioms QSB.coveredFinalChoices_after_history
#print axioms QSB.der32_count_lower
#print axioms QSB.der32_count_upper
#print axioms QSB.der32_count_exact
#print axioms QSB.der32_count_ratio
#print axioms QSB.der20_count_exact
#print axioms QSB.der20_count_ratio
#print axioms QSB.extracted_novel_round_fresh_or_puzzle
#print axioms QSB.min_roll_bounds
#print axioms QSB.comparison_selects_pool
#print axioms QSB.distinct_positions_after_roll
#print axioms QSB.selected_not_in_erased
#print axioms QSB.chooseMany_values_in_pool
#print axioms QSB.chooseMany_distinct
#print axioms QSB.chooseMany_length
#print axioms QSB.nine_selected_partition
#print axioms QSB.Layout.first_multisig_false_still_accepts
#print axioms QSB.Layout.both_multisigs_true_accept
#print axioms QSB.Layout.final_multisig_false_rejects
#print axioms QSB.Layout.first_multisig_result_irrelevant
#print axioms QSB.Layout.accepted_trace_operation_count
#print axioms QSB.Layout.accepted_trace_stack_size
#print axioms QSB.Layout.first_result_retained_below_top
#print axioms QSB.Layout.first_selection_can_reach_external_cell
#print axioms QSB.Layout.external_probe_not_full_acceptance
#print axioms QSB.Layout.matched_external_passes_first_comparison
#print axioms QSB.Layout.matched_external_fails_second_index
#print axioms QSB.Layout.last_bonus_overshoot_selects_commitment
#print axioms QSB.Layout.last_bonus_overshoot_symbolic_trace_accepts
#print axioms QSB.Bonus.canonical_region_matches_generated_program
#print axioms QSB.Bonus.region_cell
#print axioms QSB.Bonus.region_length
#print axioms QSB.Bonus.first_fresh_dummy
#print axioms QSB.Bonus.last_fresh_dummy
#print axioms QSB.Bonus.commitment_boundary
#print axioms QSB.Bonus.bounded_select_role
#print axioms QSB.Bonus.negative_index_rejected
#print axioms QSB.Bonus.oversized_index_selects_commitment
#print axioms QSB.Bonus.nonfresh_shifts_nonzero_into_dummy_slot
#print axioms QSB.Bonus.fresh_or_commitment_preserves_zero_dummy
#print axioms QSB.ByteIndex.empty_is_zero
#print axioms QSB.ByteIndex.negative_zero_is_zero
#print axioms QSB.ByteIndex.nonminimal_ten
#print axioms QSB.ByteIndex.positive_152
#print axioms QSB.ByteIndex.nonminimal_positive_152
#print axioms QSB.ByteIndex.negative_152
#print axioms QSB.ByteIndex.five_bytes_rejected
#print axioms QSB.ByteIndex.encode_zero
#print axioms QSB.ByteIndex.encode_ten
#print axioms QSB.ByteIndex.encode_positive_152
#print axioms QSB.ByteIndex.encode_negative_152
#print axioms QSB.ByteIndex.encode_zero_roundtrip
#print axioms QSB.ByteIndex.encode_152_roundtrip
#print axioms QSB.ByteIndex.nonminimal_ten_selects_dummy
#print axioms QSB.ByteIndex.nonminimal_152_selects_commitment
#print axioms QSB.ByteIndex.negative_152_cannot_roll
#print axioms QSB.ByteIndex.oversized_encoding_cannot_roll
#print axioms QSB.Multisig.too_many_signatures_fail
#print axioms QSB.Multisig.equal_counts_success_iff_pairs
#print axioms QSB.KeyRolls.rollAt_matches_symbolic_step
#print axioms QSB.KeyRolls.rollAt_preserves_shallower_cell
#print axioms QSB.KeyRolls.rollMany_preserves_marker
#print axioms QSB.KeyRolls.key_indices_safe
#print axioms QSB.KeyRolls.key_indices_length
#print axioms QSB.KeyRolls.final_signature_count_fixed
#print axioms QSB.KeyRolls.final_count_operands_ten
#print axioms QSB.KeyRolls.successful_final_pairs
#print axioms QSB.KeyRolls.generated_final_suffix
#print axioms QSB.ByteMachine.hash_compare_accepts_iff
#print axioms QSB.ByteMachine.successful_hash_comparison
#print axioms QSB.ByteMachine.run_append
#print axioms QSB.ByteMachine.run_pushes
#print axioms QSB.ByteMachine.run_pushes_overflow
#print axioms QSB.ByteMachine.add_success_requires_four_byte_operands
#print axioms QSB.ByteMachine.successful_hash_comparison_in_context
#print axioms QSB.ByteLayout.program_length
#print axioms QSB.ByteLayout.final_opcode_is_checkmultisig
#print axioms QSB.ByteLayout.fifteen_hors_comparisons
#print axioms QSB.ByteLayout.comparisons_follow_hash160
#print axioms QSB.ByteLayout.hash_comparison_positions_valid
#print axioms QSB.ByteTrace.forget_trace
#print axioms QSB.ByteWitness.witness_length
#print axioms QSB.ByteWitness.canonical_byte_run
#print axioms QSB.ByteWitness.first_round_boolean_ignored
#print axioms QSB.ByteWitness.all_fifteen_comparisons_reached
#print axioms QSB.FirstOvershoot.fixed_region_length
#print axioms QSB.FirstOvershoot.generated_region_is_pushes
#print axioms QSB.FirstOvershoot.generated_push_values_small
#print axioms QSB.FirstOvershoot.generated_region_pushes
#print axioms QSB.FirstOvershoot.generated_region_overflows
#print axioms QSB.FirstOvershoot.generated_prefix_split
#print axioms QSB.FirstOvershoot.generated_program_split_pinning
#print axioms QSB.FirstOvershoot.generated_pinning_opcodes
#print axioms QSB.FirstOvershoot.first_two_pinning_opcodes
#print axioms QSB.FirstOvershoot.generated_pinning_split_two
#print axioms QSB.FirstOvershoot.pin_signature_fits
#print axioms QSB.FirstOvershoot.oversized_initial_stack_fails_first_two
#print axioms QSB.FirstOvershoot.oversized_initial_stack_fails_pinning
#print axioms QSB.FirstOvershoot.modeled_pinning_consumes_two_keys
#print axioms QSB.FirstOvershoot.generated_prefix_after_pinning
#print axioms QSB.FirstOvershoot.generated_prefix_overflows_after_pinning
#print axioms QSB.FirstOvershoot.segment_is_first_two_selection_prefix
#print axioms QSB.FirstOvershoot.first_commitment_is_twenty_bytes
#print axioms QSB.FirstOvershoot.last_commitment_is_twenty_bytes
#print axioms QSB.FirstOvershoot.last_commitment_is_not_scriptnum
#print axioms QSB.FirstOvershoot.shifted_last_from_any_tail
#print axioms QSB.FirstOvershoot.first_index_roll
#print axioms QSB.FirstOvershoot.first_index_roll_raw
#print axioms QSB.FirstOvershoot.first_index_roll_no_external
#print axioms QSB.FirstOvershoot.external_commitment_roll
#print axioms QSB.FirstOvershoot.displaced_preimage_roll
#print axioms QSB.FirstOvershoot.retained_index_roll
#print axioms QSB.FirstOvershoot.byte_roll_matches_list_roll
#print axioms QSB.FirstOvershoot.next_index_is_lock_commitment
#print axioms QSB.FirstOvershoot.next_index_roll_full
#print axioms QSB.FirstOvershoot.second_min_rejects_commitment
#print axioms QSB.FirstOvershoot.parse_151
#print axioms QSB.FirstOvershoot.encode_303
#print axioms QSB.FirstOvershoot.parse_303
#print axioms QSB.FirstOvershoot.parse_311
#print axioms QSB.FirstOvershoot.oversized_index_clamps_to_152
#print axioms QSB.FirstOvershoot.oversized_index_min_step
#print axioms QSB.FirstOvershoot.first_index_prefix_opcodes
#print axioms QSB.FirstOvershoot.segment_split_first_index
#print axioms QSB.FirstOvershoot.first_comparison_lead_opcodes
#print axioms QSB.FirstOvershoot.before_first_comparison_split
#print axioms QSB.FirstOvershoot.opening_roll_lead_opcodes
#print axioms QSB.FirstOvershoot.before_opening_roll_split
#print axioms QSB.FirstOvershoot.segment_split_opening_roll
#print axioms QSB.FirstOvershoot.no_external_lead_opcodes
#print axioms QSB.FirstOvershoot.first_eight_split
#print axioms QSB.FirstOvershoot.segment_split_eight
#print axioms QSB.FirstOvershoot.segment_starts_with_index_push
#print axioms QSB.FirstOvershoot.first_six_split
#print axioms QSB.FirstOvershoot.segment_split_six
#print axioms QSB.FirstOvershoot.oversized_first_index_prefix
#print axioms QSB.FirstOvershoot.segment_first_push_overflows
#print axioms QSB.FirstOvershoot.duplicate_then_push_overflows
#print axioms QSB.FirstOvershoot.penultimate_capacity_segment_fails
#print axioms QSB.FirstOvershoot.oversized_first_index_without_external
#print axioms QSB.FirstOvershoot.no_external_lead_fails
#print axioms QSB.FirstOvershoot.no_external_first_eight_fails
#print axioms QSB.FirstOvershoot.no_external_segment_fails
#print axioms QSB.FirstOvershoot.opening_roll_lead_reaches
#print axioms QSB.FirstOvershoot.oversized_before_opening_roll
#print axioms QSB.FirstOvershoot.short_tail_opening_roll_fails
#print axioms QSB.FirstOvershoot.short_tail_segment_fails
#print axioms QSB.FirstOvershoot.first_comparison_lead_reaches_opening
#print axioms QSB.FirstOvershoot.oversized_before_first_comparison
#print axioms QSB.FirstOvershoot.first_selection_prefix_opcodes
#print axioms QSB.FirstOvershoot.segment_split
#print axioms QSB.FirstOvershoot.segment_split_comparison
#print axioms QSB.FirstOvershoot.overshoot_suffix_fails
#print axioms QSB.FirstOvershoot.first_selection_reaches_forced_suffix
#print axioms QSB.FirstOvershoot.matched_first_overshoot_segment_fails
#print axioms QSB.FirstOvershoot.oversized_first_overshoot_segment_fails
#print axioms QSB.FirstOvershoot.oversized_any_marker_segment_fails
#print axioms QSB.FirstOvershoot.oversized_arbitrary_tail_segment_fails
#print axioms QSB.FirstOvershoot.oversized_any_postindex_tail_segment_fails
#print axioms QSB.FirstOvershoot.generated_program_split
#print axioms QSB.FirstOvershoot.matched_first_overshoot_cannot_finish
#print axioms QSB.FirstOvershoot.matched_first_overshoot_after_pinning_fails
#print axioms QSB.FirstOvershoot.matched_external_initial_stack_rejected
#print axioms QSB.FirstOvershoot.oversized_external_initial_stack_rejected
#print axioms QSB.FirstOvershoot.oversized_any_marker_initial_stack_rejected
#print axioms QSB.FirstOvershoot.oversized_arbitrary_tail_initial_stack_rejected
#print axioms QSB.FirstOvershoot.oversized_any_postindex_tail_initial_stack_rejected
#print axioms QSB.FirstOvershoot.long_postindex_tail_rejected
#print axioms QSB.FirstOvershoot.saturated_postindex_tail_rejected
#print axioms QSB.FirstOvershoot.penultimate_postindex_tail_rejected
#print axioms QSB.FirstOvershoot.oversized_all_capacity_tails_rejected
#print axioms QSB.FirstOvershoot.oversized_initial_tail_rejected
#print axioms QSB.FirstOvershoot.oversized_first_index_rejected_given_pinning
#print axioms QSB.FirstOvershoot.accepted_first_index_below_152
#print axioms QSB.FirstIndexMap.shallow_cells_are_not_twenty_bytes
#print axioms QSB.FirstIndexMap.commitment_cells_are_twenty_bytes
#print axioms QSB.FirstIndexMap.first_pool_window_covers_region
#print axioms QSB.FirstIndexMap.signed_window_lookup
#print axioms QSB.FirstIndexMap.signed_window_cell_is_twenty_bytes
#print axioms QSB.FirstIndexMap.shallow_window_cell_not_twenty_bytes
#print axioms QSB.FirstIndexMap.signed_window_roll_has_lock_origin
#print axioms QSB.FirstIndexMap.shallow_window_cannot_match_hash160
#print axioms QSB.FirstIndexMap.fixed_region_hash_hit_has_commitment_origin
#print axioms QSB.extracted_pin_final_fresh_or_two_puzzles
#print axioms QSB.final_round_shape_total
#print axioms QSB.abstract_run_final_shape
#print axioms QSB.novel_two_puzzle_key_cases
#print axioms QSB.Game.changed_outputs_unauthorized
#print axioms QSB.Game.disclosedAt_append
#print axioms QSB.Game.disclosedAt_card_le_history
#print axioms QSB.Game.disclosedAt_card_le_min
#print axioms QSB.unauthorized_not_released
#print axioms QSB.gap_with_no_extractor
#print axioms QSB.unauthorized_under_source_extraction
#print axioms QSB.unauthorized_with_explicit_gap
#print axioms QSB.unauthorized_measure_bound_with_gap
#print axioms QSB.two_puzzle_failure_key_cases
#print axioms QSB.unauthorized_measure_bound_with_key_cases
